export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const AUTH_LOGIN = "AUTH_LOGIN"

export const EMAIL_VERIFY = "EMAIL_VERIFY"

export const SET_ALERT = "SET_ALERT"

export const RESET_ALERT = "RESET_ALERT"